import { writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const APP = process.env.APP_BASE_URL ?? "http://localhost:3000";

const TINY_PNG = Buffer.from([
  0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49,
  0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06,
  0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4, 0x89, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x44,
  0x41, 0x54, 0x78, 0x9c, 0x63, 0x00, 0x01, 0x00, 0x00, 0x05, 0x00, 0x01, 0x0d,
  0x0a, 0x2d, 0xb4, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e, 0x44, 0xae, 0x42,
  0x60, 0x82,
]);

async function main() {
  const tmpPng = join(tmpdir(), `smoke-${Date.now()}.png`);
  writeFileSync(tmpPng, TINY_PNG);
  console.log(`Wrote tiny PNG: ${tmpPng} (${TINY_PNG.length} bytes)`);

  console.log(`\n[1] POST ${APP}/api/submissions`);
  const formData = new FormData();
  formData.append("templateType", "standard");
  formData.append("sessionDate", "2026-05-20");
  formData.append("chiefComplaint", "Smoke test concern");
  formData.append("youtubeUrl", "");
  formData.append("notes", "Generated by smoke-test-upload.ts");
  formData.append(
    "presenters",
    JSON.stringify([{ fullName: "Smoke Tester", linkType: "none", handleOrUrl: "" }]),
  );
  formData.append(
    "discussants",
    JSON.stringify([{ fullName: "Smoke Reviewer", linkType: "none", handleOrUrl: "" }]),
  );
  formData.append("uploadFileName", "smoke.png");
  formData.append("uploadMimeType", "image/png");

  const createResponse = await fetch(`${APP}/api/submissions`, {
    method: "POST",
    body: formData,
  });
  const createBody = await createResponse.json();
  console.log(`    status: ${createResponse.status}`);
  console.log(`    body:`, JSON.stringify(createBody, null, 2));

  if (!createResponse.ok || !createBody.presignedUpload) {
    console.error("FAILED at create step");
    process.exit(1);
  }

  const presigned = createBody.presignedUpload;
  const submissionId = createBody.id;

  console.log(`\n[2] PUT to R2 ${presigned.uploadUrl.slice(0, 80)}...`);
  const putResponse = await fetch(presigned.uploadUrl, {
    method: "PUT",
    headers: { "Content-Type": presigned.fileMimeType },
    body: TINY_PNG,
  });
  console.log(`    status: ${putResponse.status}`);
  if (!putResponse.ok) {
    console.error(`    body:`, await putResponse.text());
    process.exit(1);
  }

  console.log(`\n[3] POST ${APP}/api/submissions/${submissionId}/confirm-upload`);
  const confirmResponse = await fetch(
    `${APP}/api/submissions/${submissionId}/confirm-upload`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        publicUrl: presigned.publicUrl,
        storageKey: presigned.storageKey,
        sanitizedFileName: presigned.sanitizedFileName,
        fileExtension: presigned.fileExtension,
        fileMimeType: presigned.fileMimeType,
        originalFileName: presigned.originalFileName ?? "smoke.png",
      }),
    },
  );
  const confirmBody = await confirmResponse.json();
  console.log(`    status: ${confirmResponse.status}`);
  console.log(`    body:`, JSON.stringify(confirmBody, null, 2));

  if (!confirmResponse.ok) {
    console.error("FAILED at confirm step");
    process.exit(1);
  }

  console.log(`\n[4] GET ${presigned.publicUrl} (verify file is publicly served)`);
  const headResponse = await fetch(presigned.publicUrl, { method: "HEAD" });
  console.log(`    status: ${headResponse.status}`);
  console.log(`    content-type: ${headResponse.headers.get("content-type")}`);
  console.log(`    content-length: ${headResponse.headers.get("content-length")}`);

  console.log(`\n✅ Smoke test passed. Submission: ${submissionId}`);
  console.log(`   Admin: ${APP}/admin/submissions/${submissionId}`);
}

main().catch((error) => {
  console.error("\n❌ Smoke test failed:");
  console.error(error);
  process.exit(1);
});
